/**
 * Seed Dataset for PRISMA RT 04 (50+ Rows of Warga, Pengurus, and Admins)
 * Clean, realistic data for RT 04 / RW 06 Kemayoran, Jakarta Pusat.
 */

export interface WargaSeedItem {
  id: string;
  nik: string;
  noKK: string;
  nama: string;
  jenisKelamin: "L" | "P";
  tempatLahir: string;
  tanggalLahir: string;
  agama: string;
  pendidikan: string;
  pekerjaan: string;
  statusPernikahan: string;
  statusKeluarga: string;
  alamat: string;
  blok: string;
  noRumah: string;
  rt: string;
  rw: string;
  telepon: string;
  email: string;
  role: "WARGA" | "PENGURUS" | "ADMIN";
  jabatanPengurus?: string;
  status: "AKTIF" | "PINDAH" | "MENINGGAL";
}

export const INITIAL_50_WARGA: WargaSeedItem[] = [
  // 1-5: Struktur Inti & Admin
  {
    id: "warga-01",
    nik: "3171011505750001",
    noKK: "3171011001010001",
    nama: "R Erry Adu Sundaru",
    jenisKelamin: "L",
    tempatLahir: "Jakarta",
    tanggalLahir: "1975-05-15",
    agama: "Islam",
    pendidikan: "S1 Hukum",
    pekerjaan: "Wiraswasta",
    statusPernikahan: "Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Jl. Bugis No. 95",
    blok: "A",
    noRumah: "1",
    rt: "04",
    rw: "06",
    telepon: "087872004448",
    email: "ketua.rt04@prisma-kemayoran.id",
    role: "ADMIN",
    jabatanPengurus: "Ketua RT 04",
    status: "AKTIF"
  },
  {
    id: "warga-02",
    nik: "3171012010920002",
    noKK: "3171011001010002",
    nama: "Swandaru Tirta",
    jenisKelamin: "L",
    tempatLahir: "Jakarta",
    tanggalLahir: "1992-10-20",
    agama: "Islam",
    pendidikan: "S1 Teknik Informatika",
    pekerjaan: "Software Engineer & IT Specialist",
    statusPernikahan: "Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Jl. Bugis No. 96",
    blok: "A",
    noRumah: "2",
    rt: "04",
    rw: "06",
    telepon: "087782380077",
    email: "swandrax@prisma-kemayoran.id",
    role: "ADMIN",
    jabatanPengurus: "Sekretaris & IT Engineer",
    status: "AKTIF"
  },
  {
    id: "warga-03",
    nik: "3171011204800003",
    noKK: "3171011001010003",
    nama: "Hj. Nurhayati",
    jenisKelamin: "P",
    tempatLahir: "Bandung",
    tanggalLahir: "1980-04-12",
    agama: "Islam",
    pendidikan: "S1 Akuntansi",
    pekerjaan: "Akuntan Publik",
    statusPernikahan: "Menikah",
    statusKeluarga: "Istri",
    alamat: "Jl. Bugis No. 98",
    blok: "A",
    noRumah: "3",
    rt: "04",
    rw: "06",
    telepon: "081388992211",
    email: "bendahara@prisma-kemayoran.id",
    role: "PENGURUS",
    jabatanPengurus: "Bendahara RT 04",
    status: "AKTIF"
  },
  {
    id: "warga-04",
    nik: "3171010808780004",
    noKK: "3171011001010004",
    nama: "Bambang Pamungkas",
    jenisKelamin: "L",
    tempatLahir: "Semarang",
    tanggalLahir: "1978-08-08",
    agama: "Islam",
    pendidikan: "SMA",
    pekerjaan: "Purnawirawan / Keamanan",
    statusPernikahan: "Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Jl. Bugis No. 100",
    blok: "A",
    noRumah: "4",
    rt: "04",
    rw: "06",
    telepon: "081299887766",
    email: "keamanan@prisma-kemayoran.id",
    role: "PENGURUS",
    jabatanPengurus: "Seksi Keamanan & Ketertiban",
    status: "AKTIF"
  },
  {
    id: "warga-05",
    nik: "3171012501850005",
    noKK: "3171011001010005",
    nama: "Dra. Siti Aminah",
    jenisKelamin: "P",
    tempatLahir: "Yogyakarta",
    tanggalLahir: "1985-01-25",
    agama: "Islam",
    pendidikan: "S1 Komunikasi",
    pekerjaan: "Guru PNS",
    statusPernikahan: "Menikah",
    statusKeluarga: "Istri",
    alamat: "Jl. Bugis No. 102",
    blok: "A",
    noRumah: "5",
    rt: "04",
    rw: "06",
    telepon: "081577665544",
    email: "humas@prisma-kemayoran.id",
    role: "PENGURUS",
    jabatanPengurus: "Seksi Humas & Hubungan Warga",
    status: "AKTIF"
  },
  // 6-20: Warga Blok A & B
  {
    id: "warga-06",
    nik: "3171011003880006",
    noKK: "3171011001010006",
    nama: "Ahmad Fauzi",
    jenisKelamin: "L",
    tempatLahir: "Jakarta",
    tanggalLahir: "1988-03-10",
    agama: "Islam",
    pendidikan: "S1 Manajemen",
    pekerjaan: "Karyawan Swasta",
    statusPernikahan: "Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Gg. Bugis No. 104",
    blok: "A",
    noRumah: "6",
    rt: "04",
    rw: "06",
    telepon: "081234567801",
    email: "ahmad.fauzi@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-07",
    nik: "3171011409900007",
    noKK: "3171011001010006",
    nama: "Rina Marlina",
    jenisKelamin: "P",
    tempatLahir: "Bogor",
    tanggalLahir: "1990-09-14",
    agama: "Islam",
    pendidikan: "D3 Kebidanan",
    pekerjaan: "Bidan",
    statusPernikahan: "Menikah",
    statusKeluarga: "Istri",
    alamat: "Gg. Bugis No. 104",
    blok: "A",
    noRumah: "6",
    rt: "04",
    rw: "06",
    telepon: "081234567802",
    email: "rina.marlina@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-08",
    nik: "3171010507820008",
    noKK: "3171011001010008",
    nama: "Budi Santoso",
    jenisKelamin: "L",
    tempatLahir: "Solo",
    tanggalLahir: "1982-07-05",
    agama: "Islam",
    pendidikan: "SMA",
    pekerjaan: "Pedagang",
    statusPernikahan: "Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Jl. Bugis No. 106",
    blok: "A",
    noRumah: "7",
    rt: "04",
    rw: "06",
    telepon: "081234567803",
    email: "budi.santoso@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-09",
    nik: "3171011902840009",
    noKK: "3171011001010008",
    nama: "Dewi Lestari",
    jenisKelamin: "P",
    tempatLahir: "Cirebon",
    tanggalLahir: "1984-02-19",
    agama: "Islam",
    pendidikan: "SMA",
    pekerjaan: "Ibu Rumah Tangga",
    statusPernikahan: "Menikah",
    statusKeluarga: "Istri",
    alamat: "Jl. Bugis No. 106",
    blok: "A",
    noRumah: "7",
    rt: "04",
    rw: "06",
    telepon: "081234567804",
    email: "dewi.lestari@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-10",
    nik: "3171012211950010",
    noKK: "3171011001010010",
    nama: "Rizky Pratama",
    jenisKelamin: "L",
    tempatLahir: "Jakarta",
    tanggalLahir: "1995-11-22",
    agama: "Islam",
    pendidikan: "S1 Desain",
    pekerjaan: "Graphic Designer",
    statusPernikahan: "Belum Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Jl. Bugis No. 108",
    blok: "B",
    noRumah: "1",
    rt: "04",
    rw: "06",
    telepon: "081234567805",
    email: "rizky.pratama@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-11",
    nik: "3171011101700011",
    noKK: "3171011001010011",
    nama: "Drs. Hendra Gunawan",
    jenisKelamin: "L",
    tempatLahir: "Medan",
    tanggalLahir: "1970-01-11",
    agama: "Kristen",
    pendidikan: "S2 Manajemen",
    pekerjaan: "Dosen",
    statusPernikahan: "Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Jl. Bugis No. 110",
    blok: "B",
    noRumah: "2",
    rt: "04",
    rw: "06",
    telepon: "081234567806",
    email: "hendra.gunawan@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-12",
    nik: "3171011504730012",
    noKK: "3171011001010011",
    nama: "Maria Magdalena",
    jenisKelamin: "P",
    tempatLahir: "Manado",
    tanggalLahir: "1973-04-15",
    agama: "Kristen",
    pendidikan: "S1 Farmasi",
    pekerjaan: "Apoteker",
    statusPernikahan: "Menikah",
    statusKeluarga: "Istri",
    alamat: "Jl. Bugis No. 110",
    blok: "B",
    noRumah: "2",
    rt: "04",
    rw: "06",
    telepon: "081234567807",
    email: "maria.magdalena@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-13",
    nik: "3171013006930013",
    noKK: "3171011001010013",
    nama: "Kevin Sanjaya",
    jenisKelamin: "L",
    tempatLahir: "Jakarta",
    tanggalLahir: "1993-06-30",
    agama: "Buddha",
    pendidikan: "S1 Bisnis",
    pekerjaan: "Pengusaha F&B",
    statusPernikahan: "Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Jl. Bugis No. 112",
    blok: "B",
    noRumah: "3",
    rt: "04",
    rw: "06",
    telepon: "081234567808",
    email: "kevin.sanjaya@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-14",
    nik: "3171010212960014",
    noKK: "3171011001010013",
    nama: "Clarissa Wijaya",
    jenisKelamin: "P",
    tempatLahir: "Surabaya",
    tanggalLahir: "1996-12-02",
    agama: "Buddha",
    pendidikan: "S1 Psikologi",
    pekerjaan: "HR Specialist",
    statusPernikahan: "Menikah",
    statusKeluarga: "Istri",
    alamat: "Jl. Bugis No. 112",
    blok: "B",
    noRumah: "3",
    rt: "04",
    rw: "06",
    telepon: "081234567809",
    email: "clarissa.wijaya@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  {
    id: "warga-15",
    nik: "3171012808890015",
    noKK: "3171011001010015",
    nama: "Fajar Nugraha",
    jenisKelamin: "L",
    tempatLahir: "Bandung",
    tanggalLahir: "1989-08-28",
    agama: "Islam",
    pendidikan: "D3 Perbankan",
    pekerjaan: "Bankir",
    statusPernikahan: "Menikah",
    statusKeluarga: "Kepala Keluarga",
    alamat: "Jl. Bugis No. 114",
    blok: "B",
    noRumah: "4",
    rt: "04",
    rw: "06",
    telepon: "081234567810",
    email: "fajar.nugraha@gmail.com",
    role: "WARGA",
    status: "AKTIF"
  },
  // 16-50 Warga Tambahan
  ...Array.from({ length: 35 }).map((_, idx) => {
    const num = idx + 16;
    const isMale = num % 2 === 0;
    const blok = num < 25 ? "B" : num < 40 ? "C" : "D";
    const noRumah = `${(num % 15) + 1}`;
    const namesMale = ["Wahyu Hidayat", "Eko Prasetyo", "Dimas Setiawan", "Aris Munandar", "Guntur Saputra", "Yoga Ananda", "Irfan Hakim", "Teguh Wibowo", "Lukman Hakim", "Ferry Irawan", "Reza Rahadian", "Bayu Skak", "Denny Sumargo", "Andre Taulany", "Sule Priatna", "Indra Bekti", "Raffi Ahmad", "Rizky Febian"];
    const namesFemale = ["Indah Permatasari", "Siti Nurhaliza", "Ratna Sari", "Putri Marino", "Chelsea Islan", "Dian Sastrowardoyo", "Maudy Ayunda", "Isyana Sarasvati", "Raisa Andriana", "Najwa Shihab", "Sri Mulyani", "Tri Rismaharini", "Retno Marsudi", "Puan Maharani", "Ayu Tingting", "Zaskia Gotik", "Lesti Kejora"];
    const name = isMale ? namesMale[idx % namesMale.length] : namesFemale[idx % namesFemale.length];
    
    return {
      id: `warga-${num < 10 ? `0${num}` : num}`,
      nik: `317101${num < 10 ? `0${num}` : num}058${num < 10 ? `0${num}` : num}00${num}`,
      noKK: `31710110010100${num < 10 ? `0${num}` : num}`,
      nama: name,
      jenisKelamin: isMale ? ("L" as const) : ("P" as const),
      tempatLahir: "Jakarta",
      tanggalLahir: `19${80 + (num % 20)}-0${(num % 9) + 1}-${(num % 28) + 1}`,
      agama: num % 5 === 0 ? "Kristen" : num % 7 === 0 ? "Katolik" : "Islam",
      pendidikan: num % 3 === 0 ? "S1" : "SMA",
      pekerjaan: num % 4 === 0 ? "Wiraswasta" : num % 2 === 0 ? "Karyawan Swasta" : "PNS",
      statusPernikahan: num > 30 ? "Menikah" : "Belum Menikah",
      statusKeluarga: isMale ? "Kepala Keluarga" : "Istri",
      alamat: `Gg. Bugis RT 04 No. ${num * 2}`,
      blok,
      noRumah,
      rt: "04",
      rw: "06",
      telepon: `081234567${num < 10 ? `0${num}` : num}`,
      email: `${name.toLowerCase().replace(/[^a-z]/g, "")}${num}@gmail.com`,
      role: "WARGA" as const,
      status: "AKTIF" as const
    };
  })
];
